spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 150MB
      max-request-size: 200MB

token:
  activation:
    time-to-live: 5
  jwt:
    secret: jWtSecreTk_e_y
    expiration: 30



service:
  course:
    user-available-amount: 5

mail:
  smtp:
    host: localhost
  send:
    to: test@email.com
    from: test@email.com

security:
  permit-all: /login,/logout,/api/user/account/register,/api/user/account/activate/*, /api/user/account/password/reset/*
server:
  port: 8080

